### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by kristjaan10** [TheOfficialFloW/gtactw_vita#3]
psp2core-1617194199-0x00000f34d3-eboot.bin
psp2core-1617195305-0x000050309f-eboot.bin.psp2dmp

did not appear at the beginning of the game but later in the game as you progress

**Comment by TheOfficialFloW** [comment]
Thanks, the filename is useless.

**Comment by kristjaan10** [comment]
I have nothing else 
the game just crashed sometimes and then restart application I continue to play 
next time i will pay attention that I have something that can help 
sorry for the inconvenience
