### ISSUE TITLE
You can go thru Ped's, Buildings and Vehicles

### ISSUE THREAD

**Issue by justalemon** [TheOfficialFloW/gtactw_vita#5]
This is a weird bug that I found. Somehow I was able to drive and walk thru Ped's, Buildings and Vehicles.

This one is vehicle and vehicle.

![2021-04-24-155700](https://user-images.githubusercontent.com/11861253/115972259-4ed1bb80-a51b-11eb-9d84-e27c2ca25df1.png)

This one is a building while on foot.

![2021-04-24-155841](https://user-images.githubusercontent.com/11861253/115972263-52fdd900-a51b-11eb-989a-e0b7496ce574.png)

And this one is on foot under the map.

![2021-04-24-161505](https://user-images.githubusercontent.com/11861253/115972265-5729f680-a51b-11eb-9931-ad7c47a4fac8.png)

* kubridge v0.1
* No fd_fix (rePatch reDux0 v3.0)
* libshacccg.suprx from PSM 2.01
* CTW .so and .obb from v1.04
* GTACTW.vpk v1.1

**Comment by TheOfficialFloW** [comment]
Don't pirate the game?

**Comment by justalemon** [comment]
That's weird, as I actually bought it on the Play Store just to install this on the Vita.

![image](https://user-images.githubusercontent.com/11861253/115972554-1501b480-a51d-11eb-959a-efc9270d4a7f.png)
![image](https://user-images.githubusercontent.com/11861253/115972564-2480fd80-a51d-11eb-809d-bd0867a67a49.png)

**Comment by Rinnegatamante** [comment]
So you got from Play Store a modded apk with noclip and money cheat enabled? Cool

**Comment by justalemon** [comment]
I just skipped the apk from the Play Store and only transferred the obb. I got the so from the money cheat but didn't mentioned the noclip thing.

Anyway, sorry for bothering you guys. I guess ill have to use the og apk from the Play Store.
